version: "2"

services:
  restria:
    links:
      - redis
      - mongodb
    build: .
    container_name: restria
    environment: 
      MONGO_URI: mongodb://localhost/restria-dev
      MONGO_URI_TEST: mongodb://localhost/restria-dev-tests
      REDIS_HOST: redis://redis
    ports:
      - "5001:80"
  redis:
    image: redis:3.2-alpine
    container_name: redis
    ports: ["6379"]
  mongodb:
    image: mongo:3.5.7
    container_name: mongodb
    ports: ["27017"]

